# Generated by Django 3.1.7 on 2021-02-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fileType',
            field=models.CharField(max_length=100),
        ),
    ]
